# Generated by Django 6.0.1 on 2026-01-31 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.PositiveIntegerField(verbose_name='Модуль')),
                ('lesson', models.PositiveIntegerField(verbose_name='Урок')),
            ],
            options={
                'ordering': ['module', 'lesson'],
                'unique_together': {('module', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('format', models.CharField(choices=[('group', 'Группа'), ('individual', 'Индивидуальный')], default='group', max_length=20, verbose_name='Формат обучения')),
                ('group_number', models.CharField(blank=True, help_text='Для группового формата', max_length=50, verbose_name='Номер группы')),
                ('first_lesson_date', models.DateField(verbose_name='Дата первого урока')),
                ('last_homework_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_homework', to='tracker.lesson', verbose_name='Последний урок с ДЗ')),
                ('last_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_last', to='tracker.lesson', verbose_name='Последний урок')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
